version: '3.8'

services:
  frontend:
    build: ./Frontend/simba  # Fixed typo "Fontend" -> "Frontend"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - cim-network

  backend:
    build: ./spring-scala-project  # Path to Spring Boot project
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cimbaDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: T@nmoy2001
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      FASTAPI_URL: "http://fastapi:8000/process"
    depends_on:
      postgres:
        condition: service_healthy
      fastapi:
        condition: service_healthy
    networks:
      - cim-network

  fastapi:
    build: ./fastapi-cim
    ports:
      - "8000:8000"
    networks:
      - cim-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cimbaDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: T@nmoy2001
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cimbaDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cim-network

volumes:
  postgres-data:

networks:
  cim-network:
    driver: bridge